databases:
  - name: projeto_django_database
    plan: free
    databaseName: projeto_django_database
    user: projeto_django

services:
  - type: web
    plan: free
    name: projeto_django
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'poetry run python -m gunicorn projeto_django.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: projeto_django_database
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4